/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/mayaashok/Documents/simulation-visualizer/frontend/public/models/car.glb 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'

type GLTFResult = GLTF & {
  nodes: {
    'NormalCar2_Cube002-Mesh': THREE.Mesh
    'NormalCar2_Cube002-Mesh_1': THREE.Mesh
    'NormalCar2_Cube002-Mesh_2': THREE.Mesh
    'NormalCar2_Cube002-Mesh_3': THREE.Mesh
    'NormalCar2_Cube002-Mesh_4': THREE.Mesh
    'NormalCar2_Cube002-Mesh_5': THREE.Mesh
    'NormalCar2_Cube002-Mesh_6': THREE.Mesh
    'NormalCar2_BackWheels_Cylinder003-Mesh': THREE.Mesh
    'NormalCar2_BackWheels_Cylinder003-Mesh_1': THREE.Mesh
    'NormalCar2_FrontLeftWheel_Cylinder015-Mesh': THREE.Mesh
    'NormalCar2_FrontLeftWheel_Cylinder015-Mesh_1': THREE.Mesh
    'NormalCar2_FrontRightWheel_Cylinder016-Mesh': THREE.Mesh
    'NormalCar2_FrontRightWheel_Cylinder016-Mesh_1': THREE.Mesh
  }
  materials: {
    LightBlue: THREE.MeshStandardMaterial
    Windows: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Grey: THREE.MeshStandardMaterial
    Headlights: THREE.MeshStandardMaterial
    'Material.007': THREE.MeshStandardMaterial
    TailLights: THREE.MeshStandardMaterial
  }
}

export function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/car.glb'
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['NormalCar2_Cube002-Mesh'].geometry} material={materials.LightBlue} />
      <mesh geometry={nodes['NormalCar2_Cube002-Mesh_1'].geometry} material={materials.Windows} />
      <mesh geometry={nodes['NormalCar2_Cube002-Mesh_2'].geometry} material={materials.Black} />
      <mesh geometry={nodes['NormalCar2_Cube002-Mesh_3'].geometry} material={materials.Grey} />
      <mesh geometry={nodes['NormalCar2_Cube002-Mesh_4'].geometry} material={materials.Headlights} />
      <mesh geometry={nodes['NormalCar2_Cube002-Mesh_5'].geometry} material={materials['Material.007']} />
      <mesh geometry={nodes['NormalCar2_Cube002-Mesh_6'].geometry} material={materials.TailLights} />
      <mesh geometry={nodes['NormalCar2_BackWheels_Cylinder003-Mesh'].geometry} material={materials.Black} />
      <mesh geometry={nodes['NormalCar2_BackWheels_Cylinder003-Mesh_1'].geometry} material={materials.Grey} />
      <mesh geometry={nodes['NormalCar2_FrontLeftWheel_Cylinder015-Mesh'].geometry} material={materials.Grey} />
      <mesh geometry={nodes['NormalCar2_FrontLeftWheel_Cylinder015-Mesh_1'].geometry} material={materials.Black} />
      <mesh geometry={nodes['NormalCar2_FrontRightWheel_Cylinder016-Mesh'].geometry} material={materials.Grey} />
      <mesh geometry={nodes['NormalCar2_FrontRightWheel_Cylinder016-Mesh_1'].geometry} material={materials.Black} />
    </group>
  )
}

useGLTF.preload('/car.glb')
