/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/red-car.glb
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'

type GLTFResult = GLTF & {
  nodes: {
    'Body_Cube001-Mesh': THREE.Mesh
    'Body_Cube001-Mesh_1': THREE.Mesh
    'Body_Cube001-Mesh_2': THREE.Mesh
    'Body_Cube001-Mesh_3': THREE.Mesh
    'FrontLeftWheel_Cylinder-Mesh': THREE.Mesh
    'FrontLeftWheel_Cylinder-Mesh_1': THREE.Mesh
    'BackLeftWheel_Cylinder001-Mesh': THREE.Mesh
    'BackLeftWheel_Cylinder001-Mesh_1': THREE.Mesh
    'BackRightWheel_Cylinder003-Mesh': THREE.Mesh
    'BackRightWheel_Cylinder003-Mesh_1': THREE.Mesh
    'FrontRightWheel_Cylinder002-Mesh': THREE.Mesh
    'FrontRightWheel_Cylinder002-Mesh_1': THREE.Mesh
  }
  materials: {
    'Material.001': THREE.MeshStandardMaterial
    'Material.004': THREE.MeshStandardMaterial
    'Material.005': THREE.MeshStandardMaterial
    'Material.006': THREE.MeshStandardMaterial
    'Material.002': THREE.MeshStandardMaterial
    'Material.003': THREE.MeshStandardMaterial
    'Material.008': THREE.MeshStandardMaterial
    'Material.007': THREE.MeshStandardMaterial
    'Material.012': THREE.MeshStandardMaterial
    'Material.011': THREE.MeshStandardMaterial
    'Material.010': THREE.MeshStandardMaterial
    'Material.009': THREE.MeshStandardMaterial
  }
}

export function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/red-car.glb'
  ) as unknown as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.25, 0]}>
      <mesh geometry={nodes['Body_Cube001-Mesh'].geometry} material={materials['Material.001']}/>
      <mesh geometry={nodes['Body_Cube001-Mesh_1'].geometry} material={materials['Material.004']}/>
      <mesh geometry={nodes['Body_Cube001-Mesh_2'].geometry} material={materials['Material.005']}/>
      <mesh geometry={nodes['Body_Cube001-Mesh_3'].geometry} material={materials['Material.006']}/>
      <mesh geometry={nodes['FrontLeftWheel_Cylinder-Mesh'].geometry} material={materials['Material.002']}/>
      <mesh geometry={nodes['FrontLeftWheel_Cylinder-Mesh_1'].geometry} material={materials['Material.003']}/>
      <mesh geometry={nodes['BackLeftWheel_Cylinder001-Mesh'].geometry} material={materials['Material.008']}/>
      <mesh geometry={nodes['BackLeftWheel_Cylinder001-Mesh_1'].geometry} material={materials['Material.007']}/>
      <mesh geometry={nodes['BackRightWheel_Cylinder003-Mesh'].geometry} material={materials['Material.012']}/>
      <mesh geometry={nodes['BackRightWheel_Cylinder003-Mesh_1'].geometry} material={materials['Material.011']}/>
      <mesh geometry={nodes['FrontRightWheel_Cylinder002-Mesh'].geometry} material={materials['Material.010']}/>
      <mesh geometry={nodes['FrontRightWheel_Cylinder002-Mesh_1'].geometry} material={materials['Material.009']}/>
      </group>
    </group>
  )
}

useGLTF.preload('/models/red-car.glb')