/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/robo.glb 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'

type GLTFResult = GLTF & {
  nodes: {
    Wheel_1001: THREE.Mesh
    Wheel_2001: THREE.Mesh
    Wheel_3001: THREE.Mesh
    Wheel_6: THREE.Mesh
    Rover_2: THREE.Mesh
    Wheel_2002: THREE.Mesh
    Wheel_3002: THREE.Mesh
  }
  materials: {
    Atlas: THREE.MeshStandardMaterial
  }
}

export function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/robo.glb'
  ) as unknown as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[7.159, 0, 0]}>
      <mesh
        geometry={nodes.Wheel_1001.geometry}
        material={materials.Atlas}
        position={[-5.363, 0.526, -1.764]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />

      <mesh
        geometry={nodes.Wheel_2001.geometry}
        material={materials.Atlas}
        position={[-8.955, 0.526, -3.3]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />

      <mesh
        geometry={nodes.Wheel_3001.geometry}
        material={materials.Atlas}
        position={[-5.363, 0.526, -3.3]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />

      <mesh
        geometry={nodes.Wheel_6.geometry}
        material={materials.Atlas}
        position={[-8.955, 0.526, -1.764]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />

      <mesh
        geometry={nodes.Rover_2.geometry}
        material={materials.Atlas}
        position={[-7.159, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />

      <mesh
        geometry={nodes.Wheel_2002.geometry}
        material={materials.Atlas}
        position={[-8.955, 0.526, 1.897]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />

      <mesh
        geometry={nodes.Wheel_3002.geometry}
        material={materials.Atlas}
        position={[-5.363, 0.526, 1.897]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      </group>
    </group>
  )
}

useGLTF.preload('/models/robo.glb')
